---
title: "Data manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS litters data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

```

## `select`

Choose some columns and not others.

```{r}
select(litters_df, group, gd0_weight)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)

#colon specifies a range of columns. 
```

```{r}
select(litters_df, -litter_number)

# the "-" says minus litter_number. can specify what we want to lose.
```

Renaming columns. 

```{r}
select(litters_df, GROUP = group, LITTer_NuMber = litter_number)

#allows to rename the columns we want to keep simultaneously 
```

```{r}
rename(litters_df, GROUP = group, LITTer_NuMber = litter_number)
#rename fn part of the dyplr packaage (in tidyverse)
```


Select helpers
find some helper fns in ?select_helper

```{r}
select(litters_df, starts_with("gd"))
#selects columns that start with gd. 
```


```{r}
select(litters_df, litter_number, everything())
#this selects litter number and keeps everything else. it moves litter number to the beginning. 
```

```{r}
relocate(litters_df, litter_number)
#does the same as the above code that uses select. This relocated it to the beginning. 
```

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
#filters the observations of gd weight if they are less than 22 (observaion of <22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
#two "=" is a test for EQUALITY. one "=" would make 22 go into gd_of_birth vector. 
```

```{r}
filter(litters_df, gd_of_birth != 20)
#exclamation is NOT EQUAL TO 
```


```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
#give AND statement. Both things true at same time.
```

```{r}
filter(litters_df, group == "Con7")
#gives the group of the character "Con7"
```

```{r}
filter(litters_df, group == "Mod8")

```

```{r}
filter(litters_df, group %in% c("Mod8", "Con7"))

#want group is either "con7" or "mod8", use %in% and list objects, but they're characters, so make sure "c" is there.
```

## `mutate`

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight, #gives weight at 18-weight at 0
  group = str_to_lower(group)    #modifies var to make everything lowercase. 
  )

#can mutate multiple things in one line
```

## `arrange`
put things in order

```{r}
arrange(litters_df, pups_born_alive)
```

```{r}
arrange(litters_df, pups_born_alive, gd0_weight)
#orders by pups born alive and then by weight
```


## `%.%`
Pipes

```{r}
litters_raw = read_csv("./data/FAS_litters.csv")
litters_clean = janitor::clean_names(litters_raw)
litters_selected = select(litters_clean, -pups_survive)
litters_mutate = mutate(litters_selected, wt_gain = gd18_weight - gd0_weight)
litters_wo_missing = drop_na(litters_mutate, wt_gain)

```

USE PIPE OPERATOR INSTEAD

```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv") %>% #shift command m
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(wt_gain)
```

