---
title: "Exploratory analysis using data summaries"
author: "Nidhi Patel"
date: "10/6/2020"
output: github_document
---

```{r setup}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

#copy and paste all this setup stuff to all the other rmarkdowns

```


### Load weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors( 
    c("USW00094728", "USC00519397", "USS0023B17S"), 
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
    mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>% 
  select(name, id, everything())


weather_df
```


### `group_by`

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  ungroup(month) #leave blank ig you want to ungroup everything. 
```

### counting things

```{r}
weather_df %>% 
  group_by(name, month) %>% #can do name or month solo or add more vars
  summarize(nobs = n())
```

we can use `count()`

```{r}
weather_df %>% 
  count(name, month, name = "n_obs")
```

**NEVER** use base R's `table`

```{r, eval = FALSE}
weather_df %>% 
  pull(month) %>% 
  table()
#don't ever use this, can't really evaluate. useless.

```

other helpful counters. 

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(), #tells us the # of observations
    n_days = n_distinct(date) #`n_distinct` is a fn in the dplyr package that will count distinct dates (max 31, bc there are 31 max in a month)
  )
```

## a digression on 2x2 tables.

```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>%
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ "" #if there is a missing value, it adds "" aka nothing
    )) %>%
      group_by(name, cold) %>% 
      summarize(count = n())
  # can reorgaize with pivot_wider.
```

other way to create 2x2 table

```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>%
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
    )
  ) %>%
  janitor::tabyl(name, cold)

##USE THIS TO CREATE 2X2 TABLES
```

### General summmaries
You can do a lot of summaries.

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prcp = mean(prcp, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE)
  )
weather_df
```

This is a dataframe. So we can make a plot

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prcp = mean(prcp, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```


Suppose you want to summarize many columns. 

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(across(prcp:tmin, mean))

```

Reminder: sometimes your results are wasier to read in another format.

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) %>% 
  knitr::kable(digits = 1) #rounds digits
```

